### ISSUE TITLE
@shigehiro-don

### ISSUE THREAD

**Issue by DogsLike** [EsProgram/uSpringBone#6]
Hi @shigehiro-don. 
It seems that the first bone (root_bone) does not rotate. Is this intentional? Is there a way to make root_bone also rotate?

最初の骨（root_bone）は回転していないようです。これは意図的ですか？ root_boneも回転させる方法はありますか？

**Comment by shigehiro-don** [comment]
Thanks for the report.

Currently uSpringBone contains a code to cancel the rotation of the root-bone.
This is the specification that was necessary previously for the benchmark.
It is unnecessary now, and we plan to respond to rotation from the root-bone.

Since it is a product under development, various changes will be included in the future.
Destructive changes are also made without notice, so be careful if you are considering introducing to your product.

-------------------------------

ご報告ありがとうございます。

現在uSpringBoneでは、ルートボーンの回転をキャンセルするコードが入っています。
これは以前、ベンチマークのために必要だった仕様です。
現在では不要であり、ルートボーンから回転に対応していく予定です。

開発途中のプロダクトなので、今後も様々な変更が入ります。
破壊的変更も予告なく行われるので、もしあなたのプロダクトへ導入を考えている場合は注意してください。

**Comment by DogsLike** [comment]
I see.Thanks.
